name: Compile Kernel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses-dev bison flex libssl-dev libelf-dev python3

    - name: Clone Kernel Source
      run: |
        git clone https://github.com/Diwas0652/Compile_Kernel.git
        cd Compile_Kernel

    - name: Configure Kernel
      run: |
        make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- dandelion_defconfig

    - name: Build Kernel
      run: |
        make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- -j$(nproc)

    - name: Check for Syntax Errors
      run: |
        python3 -m py_compile tools/dct/DrvGen.py || exit 1

    - name: Check for Multiple Definitions
      run: |
        grep -r 'yylloc' scripts/dtc/ || exit 1

    - name: Package Kernel
      run: |
        tar -czf kernel.tar.gz arch/arm64/boot/Image

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: compiled-kernel
        path: kernel.tar.gz
